import { Toaster } from '@/components/ui/sonner';
import { toasterConfig } from '@/configs/toaster-config';
import { UserProvider } from '@/providers/UserProvider';
import { Poppins } from 'next/font/google';
import { cookies } from 'next/headers';
import './globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	fallback: ['system-ui', 'sans-serif'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	const cookiesStore = await cookies();
	const userCookie = cookiesStore.get('user')?.value;
	let user = null;

	if (userCookie) {
		try {
			user = JSON.parse(userCookie);
			// if (typeof window !== 'undefined') window.user = user;
			console.log('user', user);
		} catch {
			user = null;
		}
	}

	return (
		<html lang='en' data-scroll-behavior='smooth'>
			<body className={`${poppins.variable} antialiased`}>
				<UserProvider user={user}>
					{children}
					<Toaster {...toasterConfig} />
				</UserProvider>
			</body>
		</html>
	);
}
